services:
  - type: web
    name: RITUME
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_PASSWORD
        value: 7777
      - key: DATA_DIR
        value: /data
    disk:
      name: ritume-data
      mountPath: /data
      sizeGB: 1
